name: File Reader Test
on: workflow_dispatch
jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Read README.md
        id: package
        uses: juliangruber/read-file-action@v1
        with:
          path: ./README.md
      - name: Echo README.md
        run: echo "${{ steps.package.outputs.content }}"
