name: File Reader Test
on: workflow_dispatch
jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Get XML
        id: getxml
        uses: mavrosxristoforos/get-xml-info@1.0
        with:
          xml-file: './xml/sample.xml'
          xpath: '//string'
      - name: Echo XML
        run: echo "${{ steps.getxml.outputs.info }}"
