name: First Workflow
on: workflow_dispatch
jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: Print starting
        run: echo "Starting!"
      - name: Print done
        run: echo "Done!"
